### ISSUE TITLE
JSONEditor startval instead of setValue after Initialization

### ISSUE THREAD

**Issue by germanbisurgi** [dmstr/yii2-json-editor#10]
I would like to propose to use the "startval" option during the initialization of the JSON Editor instead of setting the value after the instance creation.

Current:       new JSONEditor                 -> ready (no data yet)                -> setValue ()
Proposition: new JSONEditor(startval) -> ready (data already loaded)

This is useful for editors that implements plugins like selectize.js because they need an input that already has a value. Listening to the ready event insures that.

**Comment by schmunk42** [comment]
@germanbisurgi Is this just a thing of this widget or would it require also changes in `json-editor`?

CC: @pmk65 this is just FYI

**Comment by germanbisurgi** [comment]
it will affect only the  yii2-json-editor/src/JsonEditorWidget.php  file

**Comment by schmunk42** [comment]
@dmstr/developers If there's feedback from your side, raise your voice.

Otherwise @germanbisurgi ... go ahead ;)

**Comment by pmk65** [comment]
Isn't that feature already available or am I missing something?
In my Playground page, I initialize the editor like this, (setting the "startval" parameter if I got data):
````javascript
var opt = 'schema:' + schema + (startval.trim() ? ', startval:' + startval : '');
return 'var jseditor = new window.JSONEditor(document.querySelector("#json-editor-form"),{' + opt + '});';
````

**Comment by germanbisurgi** [comment]
The startval feature already exists in the json-editor/json-editor. But is not being leveraged in the  dmstr/yii2-json-editor/src/JsonEditorWidget.php script.

**Comment by pmk65** [comment]
@germanbisurgi My mistake. I totally overlooked that this was a different repo. 😁
