### ISSUE TITLE
Widget depends on non-standard application component "Yii::$app->settings"

### ISSUE THREAD

**Issue by cebe** [dmstr/yii2-json-editor#12]
https://github.com/dmstr/yii2-json-editor/blob/24e41099dd4d650d6023f7be945d76e1534565e3/src/JsonEditorWidget.php#L75-L78

1. this makes it unusable in environments where there is no such component
2. what does this component do and where to get it?

**Comment by schmunk42** [comment]
It's this one: https://github.com/phemellc/yii2-settings

But you're right, this does not belong in this widget @germanbisurgi

Lines 75-79 should be removed.

**Comment by cebe** [comment]
made a pull request that should keep the functionality but not break other code. If you want to remove it completely I'm fine with that too :)
